export type TestRun = {
  id: string;
  date: string;
  environment: 'STAGING' | 'BETA';
  scope: string;
  testers: string[];
  passed: number;
  failed: number;
  blocked: number;
  total: number;
  elapsed: string;
};

export type Environment = TestRun['environment'];
export type ProjectHealth = 'On Track' | 'At Risk' | 'Behind' | 'Stalled' | 'No Target Set';
export type TestCaseAuthor = { name: string; count: number };
export type DailyExecution = {
  date: string;
  dateLabel: string;
  tester: string;
  environment: Environment;
  executed: number;
  passed: number;
  failed: number;
  blocked: number;
  skipped: number;
  retest: number;
  inProgress: number;
  invalid: number;
  cancelled: number;
};

export type Project = {
  id: string;
  key: string;
  name: string;
  qa: string;
  size: string;
  stagingMtttMinutes: number | null;
  betaMtttMinutes: number | null;
  stagingStart: string;
  stagingEnd: string;
  betaStart: string;
  betaEnd: string;
  status: string;
  passed: number;
  failed: number;
  blocked: number;
  total: number;
  fresh: number;
  indexed: number;
  bugs: number;
  critical: number;
  code: string;
  domain: string;
  version: string;
  staging: number;
  beta: number;
  velocity: number;
  requiredVelocity: number;
  stagingEta: string;
  stagingDaysLeft: number;
  betaVelocity: number;
  betaRequiredVelocity: number;
  betaEta: string;
  betaDaysLeft: number;
  stagingBugs: number;
  betaBugs: number;
  canceledBugs: number;
  betaBugThresholdExceeded: boolean;
  escapedBugs: number;
  docsReady: number;
  testCaseAuthors: TestCaseAuthor[];
  testRuns: TestRun[];
  dailyExecutions: DailyExecution[];
  stagingCounts: { passed: number; failed: number; blocked: number; total: number };
  betaCounts: { passed: number; failed: number; blocked: number; total: number };
  assigneeProgress: {
    environment: Environment;
    name: string;
    activeRuns: number;
    total: number;
    executed: number;
    passed: number;
    failed: number;
    blocked: number;
    notRun: number;
    progress: number;
  }[];
};
